### ISSUE TITLE
Cannot find module useHealthkitAuthorization?

### ISSUE THREAD

**Issue by gordysc** [Kingstinct/react-native-healthkit#41]
Hello there!

I was trying to walk thru some of the examples on the README, but am getting errors when trying to use the hooks.

For example when I add this line to my project:

```ts
import { HKQuantityTypeIdentifier, useHealthkitAuthorization } from '@kingstinct/react-native-healthkit';
```

VSCode shows the following error:
```
'"@kingstinct/react-native-healthkit"' has no exported member named 'useHealthkitAuthorization'. Did you mean 'HealthkitReadAuthorization'?ts(2724)
```

Is there something else I have to configure here? I did notice in the example app we're doing it a bit differently:

```ts
import useHealthkitAuthorization from '@kingstinct/react-native-healthkit/hooks/useHealthkitAuthorization'
```

However this also resulted in the same issue on my side.

**Comment by robertherber** [comment]
Hi @gordysc,

Not quite sure why you're getting this. Are you using the latest version of the library? Could you put up a reproducible example of this happening?

**Comment by gordysc** [comment]
@robertherber I'll get a repo up later today if you want an example, but to @pin0S 's point you see the same error even on the example repo:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/4010111/206724041-564302b0-5c87-40c2-9f0e-446be9d0aecd.png">

**Comment by gordysc** [comment]
Running the example app in a simulator:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/4010111/206725736-de41221c-5024-4518-b442-de504d1546a6.png">

```
error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/luke/Personal/react-native-healthkit/src/hooks/useMostRecentQuantitySample.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project.
> 1 | import { useEffect, useState } from 'react'
  2 |
  3 | import ensureUnit from '../utils/ensureUnit'
  4 | import getMostRecentQuantitySample from '../utils/getMostRecentQuantitySample'
    at ModuleResolver.resolveDependency (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/luke/Personal/react-native-healthkit/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by pin0S** [comment]
Yeah see the same error. I'll dig in a bit more tomorrow, I can't get the `useStatisticsForQuantity` hook to work it might be related to this issue.

**Comment by robertherber** [comment]
I think this only occurs if you open the `example` folder directly in VSCode (stumbled across the same today). Try opening VSCode from the root and it should work as expected :)

If opening VSCode from the root directory doesn't solve it - let's reopen this.
