### ISSUE TITLE
Clarification of Expo plugin usage

### ISSUE THREAD

**Issue by josh-** [Kingstinct/react-native-healthkit#56]
Hi there, we're attempting to use the Expo plugin, however we're seeing the following when running the app:

```
> rn-health-test-app@1.0.0 ios
> expo start --ios

Starting project at /Users/josh/Desktop/rn-health-test-app
PluginError: Package "@kingstinct/react-native-healthkit" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
/Users/josh/Desktop/rn-health-test-app/node_modules/@kingstinct/react-native-healthkit/lib/module/index.js:1
import { Platform } from 'react-native';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePluginFile (/Users/josh/Desktop/rn-health-test-app/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:214:12)
    at resolveConfigPluginFunctionWithInfo (/Users/josh/Desktop/rn-health-test-app/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:155:14)
```

Is this what is meant by the comment in the repo "just keep in mind it will not work in Expo Go"? I note there's an open discussion in the Expo repo about supporting ESM for expo plugins: https://github.com/expo/expo/discussions/19359

## Steps to reproduce

1. Create a new expo app: `npx create-expo-app rn-health-test-app`
2. In the repo install this package: `npm i @kingstinct/react-native-healthkit`
3. Build and run: `npm run ios`

Observe error message.

**Comment by josh-** [comment]
Thanks @robertherber, which example app were you trying it with?

**Comment by aleqsio** [comment]
I can confirm this also happens for me :/ I think that the packaging process for npm does not bundle the plugin in the root of the package which should be the case for config plugins
<img width="313" alt="image" src="https://user-images.githubusercontent.com/5597580/235198164-b70d455b-1151-4a0b-9484-055f3bb741d0.png">

**Comment by robertherber** [comment]
@aleqsio Thanks for pointing this out - it was missing in the published package. Please try again with 6.1.1 :)
